Models/Venta.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SpacyWings.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Venta
    {
        public int VentaID { get; set; }
        [Required(AllowEmptyStrings = false)]
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Range(1, float.MaxValue, ErrorMessage = "Debes seleccionar un producto")]
        public decimal Importe { get; set; }
        public System.DateTime FechaVenta { get; set; }
    }
}

Controllers/VentasController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SpacyWings.Models;
using PagedList;

namespace SpacyWings.Controllers
{
    public class VentasController : Controller
    {
        private spicywingsContext db = new spicywingsContext();

        // GET: Ventas
        public ActionResult Index(int? page)
        {
            var resultado = from s in db.Venta
                            orderby s.FechaVenta descending select s;

            int pageSize = 4;
            int pageNumber = (page ?? 1);
            return View(resultado.ToPagedList(pageNumber, pageSize));
        }

        // GET: Ventas/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        public ActionResult ConsultarProductos()
        {
            return PartialView(db.Producto.ToList());
        }

        // GET: Ventas/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Ventas/Create
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "VentaID,Importe,FechaVenta")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                IPagoIVA miPago = Fabrica.CrearPago(1);

                venta.FechaVenta = DateTime.Parse(DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff"));
                venta.Importe = miPago.ObtenerMasIva(venta.Importe);
                db.Venta.Add(venta);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(venta);
        }

        // GET: Ventas/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Ventas/Edit/5
        // Para protegerse de ataques de publicación excesiva, habilite las propiedades específicas a las que quiere enlazarse. Para obtener 
        // más detalles, vea https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "VentaID,Importe,FechaVenta")] Venta venta)
        {
            if (ModelState.IsValid)
            {
                db.Entry(venta).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(venta);
        }

        // GET: Ventas/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Venta venta = db.Venta.Find(id);
            if (venta == null)
            {
                return HttpNotFound();
            }
            return View(venta);
        }

        // POST: Ventas/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Venta venta = db.Venta.Find(id);
            db.Venta.Remove(venta);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Views/Ventas/ConsultarProductos.cshtml
@model IEnumerable<SpacyWings.Models.Producto>
<div class="d-flex justify-content-center">
    @foreach (var item in Model)
    {
        <button type="button" style="margin: 10px" id="@item.Precio" name="@item.Nombre" onclick="sumar(this)" class="btn btn-outline-light">@item.Nombre</button>
    }
</div>

Views/Ventas/Create.cshtml
<!DOCTYPE html>
<html>
<head>
    @model SpacyWings.Models.Venta
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1.0">
    <title>@ViewBag.Title = Registrar venta</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="bg-dark text-white">
    <br />
    <h5 class="font-italic display-4 text-center">R e a l i z a  &nbsp; u n a  &nbsp; v e n t a</h5>

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-horizontal">
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div>
                @Html.Action("ConsultarProductos", "Ventas")
            </div>
            <br />
            <br />
            <div class="container">
                <div class="row">
                    <div class="form-group col-md-6">
                        <br />
                        <br />
                        <div class="col-md-10 d-flex justify-content-center">
                            @Html.LabelFor(model => model.Importe, htmlAttributes: new { @class = "control-label text-center" })
                        </div>
                        <div class="col-md-10 d-flex justify-content-center">
                            @Html.EditorFor(model => model.Importe, new { htmlAttributes = new { @class = "form-control bg-dark text-white", id = "ValorFinal", @readonly = "readonly", style = "margin: 10px;", placeholder = "Precio previo al IVA" } })
                            @Html.ValidationMessageFor(model => model.Importe, "", new { @class = "text-danger" })
                        </div>
                        <div class="col-md-10 d-flex justify-content-center">
                            <input type="text" style="margin: 10px" class="form-control bg-dark text-white" id="IVA" placeholder="Precio final con IVA" readonly />
                        </div>
                        <div class="col-md-10 d-flex justify-content-center">
                            <input type="submit" style="margin: 10px" value="Agregar venta" class="btn btn-outline-success" />
                        </div>
                    </div>
                    <div class="form-group col-md-6" style="overflow-y: auto; height: 200px;" id="miTabla">
                    </div>
                </div>
            </div>
        </div>
    }
    <br />
    <div>
        @Html.ActionLink("Regresar al panel principal", "Index", null, null, new { @class = "font-italic text-white" })
    </div>
    <br />
    <br />
    <h5 class="font-italic display-4 text-center">G e n e r a  &nbsp; u n a  &nbsp; f a c t u r a </h5>
    <br />
    <div class="d-flex justify-content-center">
        <input type="text" style="margin: 10px" class="form-control bg-dark text-white" id="receptor" placeholder="Nombre receptor" />
        <input type="text" style="margin: 10px" class="form-control bg-dark text-white" id="RFC" placeholder="RFC" />
        <input type="text" style="margin: 10px" class="form-control bg-dark text-white" id="Correo" placeholder="Correo" />
    </div>

    <button class="btn btn-outline-info btn-lg btn-block" onclick="generarFactura()">Generar factura</button>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

    <script>
        var monto = 0.0;
        function sumar(valor) {
            monto += parseFloat(valor.id);
            document.getElementById("ValorFinal").value = parseFloat(monto).toFixed(2);
            document.getElementById("IVA").value = parseFloat(monto * 1.16).toFixed(2);
            document.getElementById("miTabla").innerHTML += `<button type="button" style="margin: 10px" id="` + valor.id + `" name="` + valor.name + `" onclick="quitar(this)" class="btn btn-outline-warning">` + valor.name + `</button>`;
        }

        function quitar(valor) {
            valor.parentNode.removeChild(valor);
            monto = monto - parseFloat(valor.id);
            if (monto < 0) {
                monto = 0.0;
            }
            document.getElementById("ValorFinal").value = parseFloat(monto).toFixed(2);
            document.getElementById("IVA").value = parseFloat(monto * 1.16).toFixed(2);
        }

        function generarFactura() {
            var cadena = `  <h1 style="Color: blue; font-family: monospace;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; F A C T U R A &nbsp; &nbsp;&nbsp;F I S C A L </h1>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Nombre de la empresa: TastyWings</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">RFC emisor: MELM8305281H0</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Dirección emisor: Bajío 6619</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Lugar y hora de emisión: Nuevo Laredo, Tamaulipas, México. A 12:47:00 am.</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Folio Fiscal: 45117A75F1D267S</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">No. Serie: 7841225896247864</h3>
                                    <h1 style="Color: blue; font-family: monospace;">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; Datos &nbsp; &nbsp; del &nbsp; receptor</h1>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Nombre receptor: `+ document.getElementById("receptor").value + `<h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">RFC receptor: `+ document.getElementById("RFC").value + `</h3>
                                    <h3 style="Color: gray; font-family: monospace; font-size: 20px;">Correo electronico receptor: `+ document.getElementById("Correo").value + `</h3>
                                    <h1 style="Color: blue; font-family: monospace;"> &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;  C o n c e p t o s</h1>
                                    <table style="width:100%">
                                    <tr>
                                        <th style="Color: gray; font-family: monospace; font-size: 20px;">Numeración</th>
                                        <th style="Color: gray; font-family: monospace; font-size: 20px;">Descripción</th>
                                        <th style="Color: gray; font-family: monospace; font-size: 20px;">Precio unitario</th>
                                        <th style="Color: gray; font-family: monospace; font-size: 20px;">Cantidad Total</th>
                                    </tr>
                                    <tr>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">1</td>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">Servicio de comida rápida</td>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">`+ document.getElementById("ValorFinal").value + `</td>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">`+ document.getElementById("ValorFinal").value + `</td>
                                    </tr>
                                    <tr>
                                        <td>        </td>
                                        <td>        </td>
                                        <td>        </td>
                                        <td>        </td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">Precio antes de IVA</td>
                                        <td style="Color: blue; font-family: monospace; font-size: 20px;">`+ document.getElementById("ValorFinal").value + `</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td  style="Color: gray; font-family: monospace; font-size: 20px;">Porcentaje de IVA</td>
                                        <td style="Color: blue; font-family: monospace; font-size: 20px;">16%</td>
                                    </tr>
                                    <tr>
                                        <td></td>
                                        <td></td>
                                        <td style="Color: gray; font-family: monospace; font-size: 20px;">Cantidad final</td>
                                        <td style="Color: blue; font-family: monospace; font-size: 20px;">`+ document.getElementById("IVA").value + `</td>
                                    </tr>
                                    </table>
`;
            var vme = window.open("", "", "width=900, height=700");
            vme.document.write(cadena);
            vme.document.close();
            vme.focus();
            vme.print();
            vme.close();
        }
    </script>
</body>
</html>

Views/Ventas/Delete.cshtml
<!DOCTYPE html>
<html>
<head>
    @model SpacyWings.Models.Venta
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1.0">
    <title>@ViewBag.Title = Eliminar venta</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="bg-dark text-white">
    @using (Html.BeginForm())
    {

        <div class="form-horizontal">
            <br />
            <h5 class="font-italic display-4 text-center">¿ E s t á s  &nbsp; s e g u r o  &nbsp; d e &nbsp; e l i m i n a r &nbsp; l a &nbsp; v e n t a ?</h5>
            <hr />

            <br />
            <br />
        </div>

        <div>
            <div class="d-flex justify-content-center">
                <h5 class="font-italic font-weight-bold display-5 text-center">Importe pagado:</h5>
                <h5 class="font-italic text-monospace display-5 text-center">&nbsp;$@Html.DisplayFor(model => model.Importe)&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</h5>

                <br />
                <h5 class="font-italic font-weight-bold display-5 text-center"> Fecha en que se realizó la venta:</h5>
                <h5 class="font-italic text-monospace display-5 text-center">&nbsp;@Html.DisplayFor(model => model.FechaVenta)</h5>

            </div>
            <br />
            @using (Html.BeginForm())
            {
                @Html.AntiForgeryToken()

                <div class="form-actions d-flex justify-content-center">
                    <input type="submit" value="E l i m i n a r    v e n t a" class="btn btn-lg btn-outline-warning" />
                </div>
            }
            <br />
        </div>
    }

    <div>
        @Html.ActionLink("Regresar a mis ventas", "Index")
    </div>

    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
    }
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>

Views/Ventas/Details.cshtml
@model SpacyWings.Models.Venta

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Venta</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Importe)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Importe)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FechaVenta)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FechaVenta)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.VentaID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

Views/Ventas/Edit.cshtml
@model SpacyWings.Models.Venta

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Venta</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.VentaID)

        <div class="form-group">
            @Html.LabelFor(model => model.Importe, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Importe, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Importe, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.FechaVenta, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FechaVenta, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FechaVenta, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Views/Ventas/Index.cshtml
<!DOCTYPE html>
<html>
<head>
    @model PagedList.IPagedList<SpacyWings.Models.Venta>
    @using PagedList.Mvc;
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width = device-width, initial-scale = 1.0">
    <title>@ViewBag.Title = Registro de ventas</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>

<body class="bg-dark text-white">
    <br />
    <h5 class="font-italic display-4 text-center">¡ R e g i s t r a  &nbsp; u n a  &nbsp; v e n t a !</h5>
    <br />
    <p>
        @Html.ActionLink("Tomar orden...", "Create", null, new { @class = "btn btn-outline-light btn-lg btn-block" })
    </p>
    <br />
    <div>
        <table class="table text-center">
            <tr>
                <th class="text-white font-italic">
                    Importe
                </th>
                <th class="text-white font-italic">
                    Fecha de la venta
                </th>
                <th class="text-white font-italic">
                    Configuración de la venta
                </th>
            </tr>

            @foreach (var item in Model)
            {
                <tr>
                    <td class="text-white font-italic">
                        $@Html.DisplayFor(modelItem => item.Importe)
                    </td>
                    <td class="text-white font-italic">
                        @Html.DisplayFor(modelItem => item.FechaVenta)
                    </td>
                    <td>
                        @Html.ActionLink("Delete", "Delete", new { id = item.VentaID }, new { @class = "font-weight-light font-italic btn btn-outline-danger w-100" })
                    </td>
                </tr>
            }

        </table>
        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

        @Html.PagedListPager(Model, page => Url.Action("Index",
            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")

</body>
</html>